server:
  port: 9527
spring:
  #数据源
  datasource:
    username: root
    password: root123
    url: jdbc:mysql://localhost:3306/datax_web?serverTimezone=Asia/Shanghai&useLegacyDatetimeCode=false&useSSL=false&nullNamePatternMatchesAll=true&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver

  session:
    store-type: redis
    timeout: 8H
  redis:
    host: localhost
    #    password: JjWkXz2018DEV
    port: 6379

logging:
  level:
    #SQL日志
    com.wugui.dataxweb.dao.UserMapper: debug


#security:
#  oauth2:
#    resource:
#      token-info-uri: http://localhost:9528/oauth/check_token
#    client:
#      client-id: 3e3dbb44a45b11f2
#      client-secret: 123456

#security:
#  oauth2:
#    resource:
#          token-info-uri: http://localhost:9527/oauth/check_token
#    client:
#      clientId: client_2
#      id: client_2
#      clientSecret: 123456
#      userAuthorizationUri: http://localhost:9527/oauth/authorize
#      accessTokenUri: http://localhost:9527/oauth/token
#      grantType: client_credentials
#      scope: server

#management:
#    security:
#    enabled: true

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  #returnPageInfo: check

mybatis-plus:
  # mapper.xml文件扫描
  mapper-locations: classpath*:com/wugui/**/dao/mapping/*.xml
  # 实体扫描，多个package用逗号或者分号分隔
  #typeAliasesPackage: com.yibo.essyncclient.*.entity
  global-config:
    # 数据库相关配置
    db-config:
      # 主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      # 字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: NOT_NULL
      # 驼峰下划线转换
      column-underline: true
      # 逻辑删除
      logic-delete-value: 0
      logic-not-delete-value: 1
      # 数据库类型
      db-type: mysql
    banner: false
  # mybatis原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'

app:
  #  数据抽取日志文件保存路径
  etlLogDir: /xcloud/gpDataTest/data/applogs/datax-web/

dataX-path: /Users/shizhenqiang/Documents/dataX/datax/bin/

#测试图形验证码
captcha-test-code: 888888

#初始密码
init-password: 123456

zhongkeyuan:
  webmvc:
    cross:
      path-pattern: '/**'
      allowed-headers: '*'
      allowed-methods: '*'
      allowed-origins: '*'
      allow-credentials: true
      exposed-headers: 'Captcha-Request-Id'